In [8]:
import numpy as np                  
import pandas as pd                
import matplotlib.pyplot as plt    
import seaborn as sns
import mysql.connector
from mysql.connector import Error
import statsmodels.api as sm
import os

### Creacion df a partir de excell

In [3]:
# Ruta al archivo Excel
ruta_archivo = r"C:\Users\santy\Desktop\Excels sprint 4\Tablas_EAL_2023.xlsx"

# Leer las hojas especificando desde qué fila empieza cada tabla
df_eal_20 = pd.read_excel(ruta_archivo, sheet_name='EAL-20', skiprows=7)  # Empieza en fila 8 (índice 7)
df_eal_21 = pd.read_excel(ruta_archivo, sheet_name='EAL-21', skiprows=7)  # Empieza en fila 8 (índice 7)
df_eal_22 = pd.read_excel(ruta_archivo, sheet_name='EAL-22', skiprows=20) # Empieza en fila 21 (índice 20)

# Mostrar las primeras filas de cada DataFrame
print("EAL-20:")
print(df_eal_20.head(15))

print("\nEAL-21:")
print(df_eal_21.head(15))

print("\nEAL-22:")
print(df_eal_22.head(15))

EAL-20:
                                           Unnamed: 0      TOTAL  \
0                                        De dirección  11.720302
1                                De trabajo en equipo  25.101616
2            De atención al público/ trato a clientes  21.546538
3                          Administrativas de oficina  15.404153
4          Técnicas específicas del puesto de trabajo  41.047326
5   De resolución de problemas (localización de pr...  12.247244
6                              En lenguas extranjeras   8.198405
7         Generales de tecnologías de la información   12.089240
8     Profesionales de tecnologías de la información    6.125399
9   Básicas de cálculo y/o comunicación oral o esc...   1.914212
10                                             Otras   18.897610
11                                                NaN        NaN
12  (1) Una empresa puede haber señalado de una a ...        NaN

    DE 5 A 9 TRABAJADORES  DE 10 A 49 TRABAJADORES  DE 50 A 249 TRABAJADORES  \
0               10.023980                12.073995                 16.862630
1               28.781610                21.260503                 25.132275
2               22.843817                20.619421                 19.238683
3               15.530493                15.496009                 14.662943
4               36.335608                44.172620                 48.334313
5               13.544494                10.522822                 14.124045
6                5.161313                 8.189949                 20.649618
7               11.988897                11.151676                 15.902410
8                6.826706                 5.137387                  7.084068
9                2.087012                 1.688298                  1.768568
10              19.451545                18.852516                 17.215364
11                    NaN                      NaN                       NaN
12                    NaN                      NaN                       NaN

    DE 250 A 499 TRABAJADORES  MÁS DE 499 TRABAJADORES
0                   19.844835                25.893769
1                   28.460596                31.205312
2                   20.049000                26.251277
3                   14.250715                11.848825
4                   45.773785                50.408580
5                   13.719886                16.241062
6                   29.236423                29.162411
7                   19.926501                23.237998
8                    8.697428                 9.856997
9                    4.001633                 3.983657
10                  15.067374                11.644535
11                        NaN                      NaN
12                        NaN                      NaN

EAL-21:
                                           Unnamed: 0      TOTAL  INDUSTRIA  \
0                                        De dirección  11.720302  10.913108
1                                De trabajo en equipo  25.101616  19.033095
2            De atención al público/ trato a clientes  21.546538   9.733897
3                          Administrativas de oficina  15.404153  14.693309
4          Técnicas específicas del puesto de trabajo  41.047326  56.887939
5   De resolución de problemas (localización de pr...  12.089240  10.387146
6                              En lenguas extranjeras   8.198405   9.109467
7         Generales de tecnologías de la información   12.247244  11.383832
8     Profesionales de tecnologías de la información    6.125399   4.063596
9   Básicas de cálculo y/o comunicación oral o esc...   1.914212   1.191220
10                                             Otras   18.897610  19.981747
11                                                NaN        NaN        NaN
12  (1) Una empresa puede haber señalado de una a ...        NaN        NaN

    CONSTRUCCIÓN  SERVICIOS
0      13.238076  11.605946
1      21.187135  27.323574
2       5.017931  27.663706
3      11.117386  16.434234
4      60.449552  33.401095
5       5.224070  13.872169
6       2.535792   9.121675
7      10.657103  12.771708
8       2.134809   7.415336
9       1.050462   2.258273
10     21.480812  18.121834
11           NaN        NaN
12           NaN        NaN

EAL-22:
                                           Unnamed: 0   CATALUÑA  \
0                                        De dirección  11.366823
1                                De trabajo en equipo  26.903407
2            De atención al público/ trato a clientes  20.386868
3                          Administrativas de oficina  17.460612
4          Técnicas específicas del puesto de trabajo  39.387940
5   De resolución de problemas (localización de pr...  14.394127
6                              En lenguas extranjeras  11.183288
7         Generales de tecnologías de la información   12.952652
8     Profesionales de tecnologías de la información    6.827930
9   Básicas de cálculo y/o comunicación oral o esc...   2.530314
10                                             Otras   20.403366
11                                                NaN        NaN
12  (1) Una empresa puede haber señalado de una a ...        NaN

    COMUNITAT VALENCIANA  EXTREMADURA    GALICIA  MADRID (COMUNIDAD DE)  \
0               9.999650    11.690821  12.402006              13.636364
1              27.108455    25.241546  18.108623              25.665061
2              19.730174    19.371981  17.020976              27.010892
3              17.024920    17.318841  15.198813              14.620863
4              42.399776    45.217391  48.753443              36.554776
5              14.532872    16.473430   9.315630              11.232719
6               9.464891     4.202899   4.308214              13.890344
7              11.974415     7.463768   8.482237              18.857352
8               5.854392     4.106280   4.244650              11.855886
9               3.638461     3.623188   0.367258               2.704755
10             16.626472    17.391304  23.342044              15.532049
11                   NaN          NaN        NaN                    NaN
12                   NaN          NaN        NaN                    NaN

    MURCIA (REGIÓN DE)  NAVARRA (COMUNIDAD FORAL DE)  PAÍS VASCO  RIOJA, LA
0            12.331839                     11.631288   13.680059  12.147043
1            20.757612                     18.028497   23.186262  21.630261
2            22.563134                     14.539110   17.804618  19.499201
3            16.119896                     14.190172   11.141237  14.597762
4            41.267406                     44.722303   49.338592  46.190730
5            15.069625                     12.619948   11.461671  11.241343
6             5.038943                      8.287293    8.495604   5.807139
7             9.310833                     13.172434   12.981678   9.270112
8             4.000472                      6.949695    4.527155   4.848162
9             2.135945                      0.552486    0.517624   0.745871
10           17.205570                     22.099448   16.128502  16.515717
11                 NaN                           NaN         NaN        NaN
12                 NaN                           NaN         NaN        NaN

In [5]:
import pandas as pd

# Ruta al archivo Excel
ruta_archivo = r"C:\Users\santy\Desktop\Excels sprint 4\Tablas_EAL_2023.xlsx"

# --- Cargar datos ---

# EAL-20: empieza en fila 8 (índice 7)
df_eal_20 = pd.read_excel(ruta_archivo, sheet_name='EAL-20', skiprows=7)
# Renombrar primera columna
df_eal_20.rename(columns={df_eal_20.columns[0]: 'Competencias'}, inplace=True)
# Filtrar y reordenar columnas
df_eal_20 = df_eal_20[['Competencias', 'TOTAL', 'DE 250 A 499 TRABAJADORES']]

# EAL-21: empieza en fila 8 (índice 7)
df_eal_21 = pd.read_excel(ruta_archivo, sheet_name='EAL-21', skiprows=7)
df_eal_21.rename(columns={df_eal_21.columns[0]: 'Competencias'}, inplace=True)
df_eal_21 = df_eal_21[['Competencias', 'SERVICIOS']]

# EAL-22: empieza en fila 21 (índice 20)
df_eal_22 = pd.read_excel(ruta_archivo, sheet_name='EAL-22', skiprows=20)
df_eal_22.rename(columns={df_eal_22.columns[0]: 'Competencias'}, inplace=True)
df_eal_22 = df_eal_22[['Competencias', 'CATALUÑA']]

# --- Mostrar resultados ---
print("EAL-20:")
print(df_eal_20.head(12))

print("\nEAL-21:")
print(df_eal_21.head(12))

print("\nEAL-22:")
print(df_eal_22.head(12))

EAL-20:
                                         Competencias      TOTAL  \
0                                        De dirección  11.720302
1                                De trabajo en equipo  25.101616
2            De atención al público/ trato a clientes  21.546538
3                          Administrativas de oficina  15.404153
4          Técnicas específicas del puesto de trabajo  41.047326
5   De resolución de problemas (localización de pr...  12.247244
6                              En lenguas extranjeras   8.198405
7         Generales de tecnologías de la información   12.089240
8     Profesionales de tecnologías de la información    6.125399
9   Básicas de cálculo y/o comunicación oral o esc...   1.914212
10                                             Otras   18.897610
11                                                NaN        NaN

    DE 250 A 499 TRABAJADORES
0                   19.844835
1                   28.460596
2                   20.049000
3                   14.250715
4                   45.773785
5                   13.719886
6                   29.236423
7                   19.926501
8                    8.697428
9                    4.001633
10                  15.067374
11                        NaN

EAL-21:
                                         Competencias  SERVICIOS
0                                        De dirección  11.605946
1                                De trabajo en equipo  27.323574
2            De atención al público/ trato a clientes  27.663706
3                          Administrativas de oficina  16.434234
4          Técnicas específicas del puesto de trabajo  33.401095
5   De resolución de problemas (localización de pr...  13.872169
6                              En lenguas extranjeras   9.121675
7         Generales de tecnologías de la información   12.771708
8     Profesionales de tecnologías de la información    7.415336
9   Básicas de cálculo y/o comunicación oral o esc...   2.258273
10                                             Otras   18.121834
11                                                NaN        NaN

EAL-22:
                                         Competencias   CATALUÑA
0                                        De dirección  11.366823
1                                De trabajo en equipo  26.903407
2            De atención al público/ trato a clientes  20.386868
3                          Administrativas de oficina  17.460612
4          Técnicas específicas del puesto de trabajo  39.387940
5   De resolución de problemas (localización de pr...  14.394127
6                              En lenguas extranjeras  11.183288
7         Generales de tecnologías de la información   12.952652
8     Profesionales de tecnologías de la información    6.827930
9   Básicas de cálculo y/o comunicación oral o esc...   2.530314
10                                             Otras   20.403366
11                                                NaN        NaN

In [6]:
import pandas as pd

# Ruta al archivo Excel
ruta_archivo = r"C:\Users\santy\Desktop\Excels sprint 4\Tablas_EAL_2023.xlsx"

# --- Cargar y preparar EAL-20 ---
df_eal_20 = pd.read_excel(ruta_archivo, sheet_name='EAL-20', skiprows=7)
df_eal_20.rename(columns={df_eal_20.columns[0]: 'Competencias'}, inplace=True)
df_eal_20 = df_eal_20[['Competencias', 'TOTAL', 'DE 250 A 499 TRABAJADORES']]
df_eal_20.rename(columns={
    'TOTAL': 'total empresas',
    'DE 250 A 499 TRABAJADORES': 'EMPRESAS DE 250 A 499 TRABAJADORES'
}, inplace=True)

# --- Cargar y preparar EAL-21 ---
df_eal_21 = pd.read_excel(ruta_archivo, sheet_name='EAL-21', skiprows=7)
df_eal_21.rename(columns={df_eal_21.columns[0]: 'Competencias'}, inplace=True)
df_eal_21 = df_eal_21[['Competencias', 'SERVICIOS']]
df_eal_21.rename(columns={
    'SERVICIOS': 'EMPRESAS SECTOR SERVICIOS'
}, inplace=True)

# --- Cargar y preparar EAL-22 ---
df_eal_22 = pd.read_excel(ruta_archivo, sheet_name='EAL-22', skiprows=20)
df_eal_22.rename(columns={df_eal_22.columns[0]: 'Competencias'}, inplace=True)
df_eal_22 = df_eal_22[['Competencias', 'CATALUÑA']]
df_eal_22.rename(columns={
    'CATALUÑA': 'EMPRESAS COMUNIDAD CATALUÑA'
}, inplace=True)

# --- Unir los tres DataFrames ---
df_final = df_eal_20.merge(df_eal_21, on='Competencias', how='inner')
df_final = df_final.merge(df_eal_22, on='Competencias', how='inner')

# --- Mostrar resultado ---
print("DataFrame Final:")
df_final.head(15)

DataFrame Final:

,Competencias,total empresas,EMPRESAS DE 250 A 499 TRABAJADORES,EMPRESAS SECTOR SERVICIOS,EMPRESAS COMUNIDAD CATALUÑA
0,De dirección,11.720302,19.844835,11.605946,11.366823
1,De trabajo en equipo,25.101616,28.460596,27.323574,26.903407
2,De atención al público/ trato a clientes,21.546538,20.049000,27.663706,20.386868
3,Administrativas de oficina,15.404153,14.250715,16.434234,17.460612
4,Técnicas específicas del puesto de trabajo,41.047326,45.773785,33.401095,39.387940
5,De resolución de problemas (localización de pr...,12.247244,13.719886,13.872169,14.394127
6,En lenguas extranjeras,8.198405,29.236423,9.121675,11.183288
7,Generales de tecnologías de la información,12.089240,19.926501,12.771708,12.952652
8,Profesionales de tecnologías de la información,6.125399,8.697428,7.415336,6.827930
9,Básicas de cálculo y/o comunicación oral o esc...,1.914212,4.001633,2.258273,2.530314
10,Otras,18.897610,15.067374,18.121834,20.403366
11,NaN,NaN,NaN,NaN,NaN
12,(1) Una empresa puede haber señalado de una a ...,NaN,NaN,NaN,NaN

In [7]:
# Ruta al archivo Excel
ruta_archivo = r"C:\Users\santy\Desktop\Excels sprint 4\Tablas_EAL_2023.xlsx"

# --- Cargar y preparar EAL-20 ---
df_eal_20 = pd.read_excel(ruta_archivo, sheet_name='EAL-20', skiprows=7)
df_eal_20.rename(columns={df_eal_20.columns[0]: 'Competencias'}, inplace=True)
df_eal_20 = df_eal_20[['Competencias', 'TOTAL', 'DE 250 A 499 TRABAJADORES']]
df_eal_20.rename(columns={
    'TOTAL': 'total empresas',
    'DE 250 A 499 TRABAJADORES': 'EMPRESAS DE 250 A 499 TRABAJADORES'
}, inplace=True)

# --- Cargar y preparar EAL-21 ---
df_eal_21 = pd.read_excel(ruta_archivo, sheet_name='EAL-21', skiprows=7)
df_eal_21.rename(columns={df_eal_21.columns[0]: 'Competencias'}, inplace=True)
df_eal_21 = df_eal_21[['Competencias', 'SERVICIOS']]
df_eal_21.rename(columns={
    'SERVICIOS': 'EMPRESAS SECTOR SERVICIOS'
}, inplace=True)

# --- Cargar y preparar EAL-22 ---
df_eal_22 = pd.read_excel(ruta_archivo, sheet_name='EAL-22', skiprows=20)
df_eal_22.rename(columns={df_eal_22.columns[0]: 'Competencias'}, inplace=True)
df_eal_22 = df_eal_22[['Competencias', 'CATALUÑA']]
df_eal_22.rename(columns={
    'CATALUÑA': 'EMPRESAS COMUNIDAD CATALUÑA'
}, inplace=True)

# --- Unir los tres DataFrames ---
df_final = df_eal_20.merge(df_eal_21, on='Competencias', how='inner')
df_final = df_final.merge(df_eal_22, on='Competencias', how='inner')

# --- Eliminar filas con valores NaN ---
df_final.dropna(inplace=True)

# --- Mostrar resultado ---
print("DataFrame Final:")
df_final.head(20)

DataFrame Final:

,Competencias,total empresas,EMPRESAS DE 250 A 499 TRABAJADORES,EMPRESAS SECTOR SERVICIOS,EMPRESAS COMUNIDAD CATALUÑA
0,De dirección,11.720302,19.844835,11.605946,11.366823
1,De trabajo en equipo,25.101616,28.460596,27.323574,26.903407
2,De atención al público/ trato a clientes,21.546538,20.049000,27.663706,20.386868
3,Administrativas de oficina,15.404153,14.250715,16.434234,17.460612
4,Técnicas específicas del puesto de trabajo,41.047326,45.773785,33.401095,39.387940
5,De resolución de problemas (localización de pr...,12.247244,13.719886,13.872169,14.394127
6,En lenguas extranjeras,8.198405,29.236423,9.121675,11.183288
7,Generales de tecnologías de la información,12.089240,19.926501,12.771708,12.952652
8,Profesionales de tecnologías de la información,6.125399,8.697428,7.415336,6.827930
9,Básicas de cálculo y/o comunicación oral o esc...,1.914212,4.001633,2.258273,2.530314
10,Otras,18.897610,15.067374,18.121834,20.403366

In [11]:
# Ruta base del archivo de 2023
ruta_base = r"C:\Users\santy\Desktop\Excels sprint 4\Tablas_EAL_2023.xlsx"
nombre_base = os.path.basename(ruta_base)
directorio = os.path.dirname(ruta_base)

# Extraer nombre base sin el año ni extensión
nombre_sin_año = nombre_base.replace("2023.xlsx", "")  # <- corregido aquí

# Lista de años a procesar
años = [2023, 2022, 2021, 2020, 2019]

# Lista para guardar los DataFrames procesados
lista_df = []

for año in años:
    # Construir la ruta del archivo de ese año
    ruta_archivo = os.path.join(directorio, f"{nombre_sin_año}{año}.xlsx")
    
    # --- Cargar y preparar EAL-20 ---
    df_eal_20 = pd.read_excel(ruta_archivo, sheet_name='EAL-20', skiprows=7)
    df_eal_20.rename(columns={df_eal_20.columns[0]: 'Competencias'}, inplace=True)
    df_eal_20 = df_eal_20[['Competencias', 'TOTAL', 'DE 250 A 499 TRABAJADORES']]
    df_eal_20.rename(columns={
        'TOTAL': 'total empresas',
        'DE 250 A 499 TRABAJADORES': 'EMPRESAS DE 250 A 499 TRABAJADORES'
    }, inplace=True)

    # --- Cargar y preparar EAL-21 ---
    df_eal_21 = pd.read_excel(ruta_archivo, sheet_name='EAL-21', skiprows=7)
    df_eal_21.rename(columns={df_eal_21.columns[0]: 'Competencias'}, inplace=True)
    df_eal_21 = df_eal_21[['Competencias', 'SERVICIOS']]
    df_eal_21.rename(columns={
        'SERVICIOS': 'EMPRESAS SECTOR SERVICIOS'
    }, inplace=True)

    # --- Cargar y preparar EAL-22 ---
    df_eal_22 = pd.read_excel(ruta_archivo, sheet_name='EAL-22', skiprows=20)
    df_eal_22.rename(columns={df_eal_22.columns[0]: 'Competencias'}, inplace=True)
    df_eal_22 = df_eal_22[['Competencias', 'CATALUÑA']]
    df_eal_22.rename(columns={
        'CATALUÑA': 'EMPRESAS COMUNIDAD CATALUÑA'
    }, inplace=True)

    # --- Unir los tres DataFrames ---
    df_final = df_eal_20.merge(df_eal_21, on='Competencias', how='inner')
    df_final = df_final.merge(df_eal_22, on='Competencias', how='inner')

    # Eliminar filas con NaN
    df_final.dropna(inplace=True)

    # Añadir columna del año al inicio
    df_final.insert(0, 'Año', año)

    # Agregar a la lista
    lista_df.append(df_final)

# --- Concatenar todos los años en un solo DataFrame ---
df_todos_los_años = pd.concat(lista_df, ignore_index=True)

# --- Mostrar resultado final ---
print("DataFrame combinado con todos los años:")
df_todos_los_años.head(70)

DataFrame combinado con todos los años:

,Año,Competencias,total empresas,EMPRESAS DE 250 A 499 TRABAJADORES,EMPRESAS SECTOR SERVICIOS,EMPRESAS COMUNIDAD CATALUÑA
0,2023,De dirección,11.720302,19.844835,11.605946,11.366823
1,2023,De trabajo en equipo,25.101616,28.460596,27.323574,26.903407
2,2023,De atención al público/ trato a clientes,21.546538,20.049000,27.663706,20.386868
3,2023,Administrativas de oficina,15.404153,14.250715,16.434234,17.460612
4,2023,Técnicas específicas del puesto de trabajo,41.047326,45.773785,33.401095,39.387940
5,2023,De resolución de problemas (localización de pr...,12.247244,13.719886,13.872169,14.394127
6,2023,En lenguas extranjeras,8.198405,29.236423,9.121675,11.183288
7,2023,Generales de tecnologías de la información,12.089240,19.926501,12.771708,12.952652
8,2023,Profesionales de tecnologías de la información,6.125399,8.697428,7.415336,6.827930
9,2023,Básicas de cálculo y/o comunicación oral o esc...,1.914212,4.001633,2.258273,2.530314
10,2023,Otras,18.897610,15.067374,18.121834,20.403366
11,2022,De dirección,13.528020,24.226804,14.900472,13.059921
12,2022,De trabajo en equipo,24.281396,29.053421,27.229362,26.491722
13,2022,De atención al público/ trato a clientes,23.473546,18.134958,31.009624,23.972603
14,2022,Administrativas de oficina,15.630788,11.715089,17.280770,14.425582
15,2022,Técnicas específicas del puesto de trabajo,41.638602,53.608247,33.125710,42.137995
16,2022,De resolución de problemas (localización de pr...,11.690887,15.557638,12.085600,11.681654
17,2022,En lenguas extranjeras,8.894352,28.865979,10.159603,9.969325
18,2022,Generales de tecnologías de la información,12.004092,20.899719,13.186682,14.135642
19,2022,Profesionales de tecnologías de la información,5.492456,8.200562,6.321358,6.422809
20,2022,Básicas de cálculo y/o comunicación oral o esc...,1.601388,4.404873,1.997728,1.945542
21,2022,Otras,19.598053,13.870665,18.458366,17.318682
22,2021,De dirección,18.460771,26.426265,19.073773,21.411396
23,2021,De trabajo en equipo,25.838363,29.440258,26.983225,26.879247
24,2021,De atención al público/ trato a clientes,20.208615,18.353068,26.405576,15.381600
25,2021,Administrativas de oficina,18.017760,13.078579,18.718515,19.798745
26,2021,Técnicas específicas del puesto de trabajo,46.677170,52.529602,39.182766,47.004705
27,2021,De resolución de problemas (localización de pr...,11.202205,13.024758,11.060586,10.094093
28,2021,En lenguas extranjeras,7.862089,30.893434,8.701676,11.231051
29,2021,Generales de tecnologías de la información,13.936823,22.604952,15.801141,16.194459
30,2021,Profesionales de tecnologías de la información,5.719140,11.410118,6.528922,6.949817
31,2021,Básicas de cálculo y/o comunicación oral o esc...,1.973054,3.821313,2.390172,1.351281
32,2021,Otras,13.931390,15.823466,13.353417,12.467329
33,2020,De dirección,15.275113,23.032830,15.581089,10.595409
34,2020,De trabajo en equipo,21.726806,22.928609,23.000220,18.798521
35,2020,De atención al público/ trato a clientes,18.633907,18.603439,23.863803,18.531969
36,2020,Administrativas de oficina,11.114247,10.057322,11.129611,9.156032
37,2020,Técnicas específicas del puesto de trabajo,53.492995,62.793121,47.535495,53.993270
38,2020,De resolución de problemas (localización de pr...,11.671119,13.757165,12.245682,13.973945
39,2020,En lenguas extranjeras,9.327614,29.963523,9.969628,13.670743
40,2020,Generales de tecnologías de la información,11.858625,22.355393,12.731448,13.061007
41,2020,Profesionales de tecnologías de la información,4.751602,10.369984,5.549254,5.850798
42,2020,De cálculo o lingüísticas,0.593872,1.354872,0.700746,0.749675
43,2020,De comunicación oral o escrita,1.390927,3.387181,1.609155,1.575984
44,2020,Otras,16.351858,13.913497,16.999049,21.507347
45,2019,De dirección,16.637833,30.256162,17.043337,18.483748
46,2019,De trabajo en equipo,26.441100,30.352827,28.287132,28.009346
47,2019,De atención al público/ trato a clientes,26.413420,25.374577,33.693071,24.191597
48,2019,Administrativas de oficina,14.990454,14.644756,14.500015,11.981057
49,2019,Técnicas específicas del puesto de trabajo,50.349055,54.277429,44.117732,47.584178
50,2019,De resolución de problemas (localización de pr...,12.484990,13.968101,12.596441,12.980348
51,2019,En lenguas extranjeras,9.909917,34.702755,10.750341,14.586723
52,2019,Generales de tecnologías de la información,11.100980,23.537941,11.545093,11.956023
53,2019,Profesionales de tecnologías de la información,5.903616,9.424843,6.684857,8.015188
54,2019,Básicas de cálculo y/o comunicación oral o esc...,1.338012,2.996617,1.582538,1.207911
55,2019,Otras,10.976419,13.484775,9.644423,12.412901